# Site settings
title: Calvin Lau's Portfolio # site title
lang: en-US # default lang
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Calvin Lau # author name
  bio: >- # tell to the world
    Welcome to my portfolio! This is where you can find all my projects and find my contact details
  github: eddyxwong # github username
  facebook: calvin.lau.7773 # facebook username
  email: eddyxwong@gmail.com # email address
  avatar: /assets/img/avatar.gif # change with your own avatar

# URL settings
url: #
baseurl: #
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 4

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
